Repository gusto-umc/Gusto-Server, pull requests merged in 2024-05, with the labels that each got.

#256 feat: 프로필 수정 API에 닉네임 필드 포함
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#257 release: 0.2.3
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy

#264 Bug: hasNext 오타 수정
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RoutePagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :bug: Bug

#260 refactor : 가게 다중 조회를 위해 가게 조회 API 수정
  gusto/.idea/deployment.xml
  gusto/.idea/misc.xml
  gusto/.idea/sshConfigs.xml
  gusto/.idea/webServers.xml
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#263 feat : 카테고리 속 가게 정렬 기준 추가 API
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
Labels: :sparkles: Feature

#265 feat: sign-out
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#268 refactor: 초대 코드로 그룹 정보 조회 API 엔드포인트를 GET에서 POST로 변경
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
Labels: :hammer_and_wrench: Refactor

#269 release: 0.2.5
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
Labels: :earth_asia: Deploy
