Repository gusto-umc/Gusto-Server, pull requests merged in 2024-01, with the labels that each got.

#6 feat : 엔티티 생성 (MyCategory, Review, User) 및 양방향 처리
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/gusto.iml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/Pin.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/HashTag.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Liked.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Tagging.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Follow.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/global/common/BaseEntity.java
  gusto/src/main/java/com/umc/gusto/global/common/PublishStatus.java
Labels: :gear: Setting

#15 refactor: 일부 엔티티의 field의 @Column annotation 옵션 수정
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :bug: Bug, :hammer_and_wrench: Refactor

#17 feat : 내 카테고리 CRUD API 작성
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
Labels: :bug: Bug, :hammer_and_wrench: Refactor, :sparkles: Feature

#20 feat: 소셜 로그인 및 회원가입
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/user/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/AuthUser.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/CustomOAuth2User.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/Tokens.java
  gusto/src/main/java/com/umc/gusto/global/config/RedisConfig.java
  gusto/src/main/java/com/umc/gusto/global/util/RedisService.java
Labels: :sparkles: Feature

#27 fix: UserRepository가 중복 생성된 문제
  gusto/src/main/java/com/umc/gusto/domain/user/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/global/auth/UserDetailsService.java
Labels: :bug: Bug

#25 feat : RestControllor를 이용한 에러 핸들러
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
  gusto/src/main/java/com/umc/gusto/global/exception/GeneralException.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/TempException.java
  gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
Labels: :sparkles: Feature
