Repository gusto-umc/Gusto-Server, pull requests merged in 2024-02, with the labels that each got.

#31 fix: 소셜 로그인 동의 여부 관련 버그, provider Id가 노출되던 문제
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
Labels: :bug: Bug

#38 fix: social 로그인 시 Age 포메팅 오류 수정
  gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
Labels: :bug: Bug

#34 feat: 랜덤 닉네임 생성
  gusto/src/main/java/com/umc/gusto/domain/user/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/NicknameBucket.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FirstLogInResponse.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
Labels: :sparkles: Feature

#44 release: 0.1.0-alpha.1
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/NicknameBucket.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FirstLogInResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationFailureHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/AuthUser.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/CustomOAuth2User.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/Tokens.java
  gusto/src/main/java/com/umc/gusto/global/config/RedisConfig.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
  gusto/src/main/java/com/umc/gusto/global/exception/GeneralException.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/TempException.java
  gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
  gusto/src/main/java/com/umc/gusto/global/util/RedisService.java
Labels: :earth_asia: Deploy

#39 feat: aws s3 이미지 저장
  gusto/src/main/java/com/umc/gusto/global/config/S3Config.java
  gusto/src/main/java/com/umc/gusto/global/util/S3Controller.java
  gusto/src/main/java/com/umc/gusto/global/util/S3Service.java
Labels: :sparkles: Feature

#33 feat : 위치 기반 내 카테고리 조회 API
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryCommandServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/common/BaseEntity.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/NoPermission.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/NotFoundException.java
Labels: :sparkles: Feature

#42 루트 &루트 리스트 생성, 삭제
  gusto/.idea/.gitignore
  gusto/.idea/compiler.xml
  gusto/.idea/gradle.xml
  gusto/.idea/jarRepositories.xml
  gusto/.idea/misc.xml
  gusto/.idea/modules.xml
  gusto/.idea/modules/gusto.main.iml
  gusto/.idea/uiDesigner.xml
  gusto/.idea/vcs.xml
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :sparkles: Feature

#36 feat: 먹스또 프로필 조회 API
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileRes.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#51 fix: 닉네임 중복체크 API의 method 변경(POST -> GET)
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
Labels: :hammer_and_wrench: Refactor

#40 feat : Review 기본 CRUD API
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/ReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/HashTagRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/TaggingRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :sparkles: Feature

#41 feat: Group CRUD API
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/Group.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/GroupMember.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupMemberRequestDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupRequestDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupMemberResponseDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupResponseDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
Labels: :sparkles: Feature

#50 feat: social login 결과 redirect
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/model/OAuthAttributes.java
Labels: :hammer_and_wrench: Refactor, :sparkles: Feature

#69 hotfix: 닉네임 중복 확인 API 버그 수정
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :bug: Bug

#54 refactor: 단일 이미지, 다수 이미지 로직 분리
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/global/util/S3Controller.java
  gusto/src/main/java/com/umc/gusto/global/util/S3Service.java
Labels: :hammer_and_wrench: Refactor

#55 refactor: 리뷰 CRUD response, request 수정 & 리뷰 하드 삭제 -> 소프트 삭제로 수정, 리뷰 생성 수정 시 이미지 저장
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor, :sparkles: Feature

#61 refactor: Group CRUD 관련 리펙토링
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/Group.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/GroupMember.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupMemberRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupMemberRequestDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupRequestDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/PostGroupRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/UpdateGroupRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupMemberResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupMemberResponseDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupResponseDto.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/PostGroupResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/UpdateGroupResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#68 refactor : MyCategory CRUD 공통 리펙토리
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#84 feat: Group 목록 및 구성원 조회 API
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupsResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
Labels: :sparkles: Feature

#92 feat: Group 참여 및 탈퇴 API
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/JoinGroupRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/InvitationCodeRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#105 refactor: User Entity
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :hammer_and_wrench: Refactor

#101 feat: Group 소유권 이전 API
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/Group.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/TransferOwnershipRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/TransferOwnershipResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#89 feat: Group 초대코드 생성 및 조회 API
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/entity/InvitationCode.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetInvitationCodeResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/InvitationCodeRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#111 hotfix: 괄호 생략으로 인한 오류 수정
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
Labels: :bug: Bug

#91 feat: 루트 조회 로직(상세,거리)
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
Labels: :sparkles: Feature

#72 feat: 토큰 검증 시 유저 status 검증 / fix: userid() to userId()
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/global/auth/UserDetailsService.java
Labels: :bug: Bug, :sparkles: Feature

#74 feat: User Domain - Follow 관련 API
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FollowResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#82 feat: 회원 가입 시 profile Image 업로드 기능 / fix: default image 처리 오류
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FirstLogInResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :bug: Bug, :sparkles: Feature

#83 feat: User Domain - Profile 관련 API
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileRes.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/PublishingInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/util/S3Service.java
Labels: :sparkles: Feature

#94 feat: 리뷰 모아보기- 인스타뷰, 타임라인 뷰, 캘린더뷰 API 생성
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/ReviewCalViewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/ReviewViewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/BasicViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CalendarViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsOfCalResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsOfInstaResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsOfTimelineResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/TimelineViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :sparkles: Feature

#100 feat: 먹스또 랜덤 피드 API 생성
  gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
Labels: :sparkles: Feature

#103 refactor: 리뷰 수정 시 이미지를 요청에서 주지 않았을 경우 오류 발생하는 부분 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#98 feat: GroupList API
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/request/GroupListRequest.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GroupListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#117 hotfix:resolve conflicts(제외된 import문, 중복된 명칭)
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
Labels: :bug: Bug

#85 feat : 가게 정보 조회 API / refactor : OpeningHours BusinessDay 형 변환, LIMIT 사용
  .idea/modules/gusto.main.iml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/PinController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreateMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreatePinRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/DeleteMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/PinRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/UpdateMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PinByMyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PinResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Category.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/OpeningHours.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetReviewsResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/OpeningHoursRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#87 feat : 현재 지역의 카테고리 별 찜한 가게 목록 API
  .idea/modules/gusto.main.iml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Category.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoresInMapResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#110 refactor : nickname이 user의 nickname인 경우 PRIVATE 카테고리 조회 가능 / user entity의 publishCategory를 통해 공개 여부 조정
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#107 refactor: 리뷰를 쓴 유저의 리뷰 공개 여부에 따라 리뷰 조회하도록 수정(리뷰 1건 조회 API)
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/PrivateItemException.java
Labels: :hammer_and_wrench: Refactor

#112 feat: 다른 유저의 리뷰 모아보기
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :sparkles: Feature

#114 refactor: 방문 날짜가 같은 경우, 생성 날짜를 기준으로 정렬 후 페이징 처리
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#131 chore: city, town 엔티티의 code field 길이 변경
  gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java
Labels: :hammer_and_wrench: Refactor

#132 release: 0.1.0-alpha.4
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/exception/customException/PrivateItemException.java
Labels: :earth_asia: Deploy

#120 refactor : 가게 상세 조회 시 리뷰 날짜별 분류 처리
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#134 refactor : 유효성 검사 & 필요 없는 파일 삭제
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreatePinRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/MyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/UpdateMyCategoryRequest.java
Labels: :hammer_and_wrench: Refactor

#143 refactor : 가게 조회 시 날짜 별 리뷰 분류 처리 삭제
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#121 refactor: 리뷰 생성 할 때 이미지가 null인데 이미지 저장을 시도하는 경우 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#122 refactor: @Valid 에러를 체크하지 못하는 부분 수정
  gusto/src/main/java/com/umc/gusto/global/exception/ExceptionResponse.java
  gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
Labels: :hammer_and_wrench: Refactor

#115 feat : 그룹 내 루트 조회, 루트 수정 API
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/RouteList.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/ModifyRoueListRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/ModifyRouteRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#130 feat: access token 재발급 API
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
  gusto/src/main/java/com/umc/gusto/global/util/RedisService.java
Labels: :sparkles: Feature

#136 refactor: 그룹 목록 조회 시 그룹장 여부 반환
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/GetGroupsResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#138 feat: 현재 지역의 찜한 식당 방문 여부 조회 API
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetPinStoreResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/UnvisitedStoresResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/VisitedStoresResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#140 refactor : 내 카테고리 조회 시 myCategoryScript 추가 조회 / fix : 카테고리 수정 시 중복이름 버그 수정
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreateMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
Labels: :bug: Bug, :hammer_and_wrench: Refactor

#144 feat: 프로필 정보 조회 시 프로필 이미지 return / refactor: default img 관련 처리
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/ProfileResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
Labels: :hammer_and_wrench: Refactor, :sparkles: Feature

#145 refactor: 리뷰 생성 시 이미지 값이 null이면 디폴트 이미지로 저장하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#123 bug: 루트 조회 , 루트 삭제 시 로직 오류 수정
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :bug: Bug

#147 feat: 먹스또 프로필 - 본인 조회 시, 닉네임이 아닌 키워드를 사용하도록 대체
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#149 hotfix: 리뷰 모아보기 API 요청 시, 리뷰가 없는 경우 빈 리스트와 hasNext = false를 응답하도록 수정 & 모아보기 관련 API 4개 requestbody대신 queryParam으로 수정 & 캘린더 뷰 리뷰모아보기 API 응답에 방문날짜 포함
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CalendarViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsOfCalResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :bug: Bug

#150 refactor: UUID가 url에 포함되어있는 부분을 nickName으로 수정
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#151 fix: 해시태그 id가 아닌 엔티티 주소 값이 넘어가는 상황 수정
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :bug: Bug

#153 release: 0.1.0-alpha.6
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CalendarViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsOfCalResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :earth_asia: Deploy

#141 feat: 기존 루트에 식당 추가 / 그룹 내 루트 삭제
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#154 feat: 먹스또 프로필 조회 시 팔로잉 수 반환
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FeedProfileResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#156 feat: 초대 코드로 그룹 참여 및 중복 가입 예외 처리 추가
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#161 release: 0.1.0-alpha.7
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteListRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/FeedProfileResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#159 refactor : 위치 여부에 상관 없이 API 통일 / 내 카테고리 조회 시 토큰으로 처리
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#164 feat: 피드 검색 기능
  gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/SearchFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
Labels: :sparkles: Feature

#166 feat: 가게 검색 기능
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#168 refactor: (재업로드)방문 날짜가 같은 경우, 생성 날짜를 기준으로 정렬 후 페이징 처리
  .idea/compiler.xml
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#169 refactor : 리뷰 이미지가 없는 경우 "" 처리
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#171 release: 0.1.0-alpha.8
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/PinController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/CreatePinResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/SearchFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoresInMapResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#174 fix: 리뷰 생성과 조회 시 해시 태그가 없으면 에러 발생하는 부분 수정
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :bug: Bug

#175 refactor: 리뷰 대표 이미지만 넘기도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/BasicViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CalendarViewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java
Labels: :hammer_and_wrench: Refactor

#178 refactor : store entity 내에 categoryString 추가
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
Labels: :hammer_and_wrench: Refactor

#182 hotfix : longitude DOUBLE 범위 수정 취소
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
Labels: :warning: invalid

#183 hotfix : logitude DOUBLE 범위 수정 시 categoryString 삭제 실수 해결
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
Labels: :bug: Bug, :warning: invalid

#191 refactor : 가게 상세 조회 시 카테고리 categoryString을 조회
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#192 refactor : 리뷰 조회 시 status을 거치도록 수정 / 방문 날짜를 기준으로 리뷰 조회
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#189 fix: 피드 상세 보기 API에서 리뷰의 해시태그가 없을 때 상세보기 에러가 발생하는 부분 해결 & 프론트에서 편하게 List로 해시태그 id값 반환
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/FeedDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
Labels: :bug: Bug

#193 refactor: response 해시태그 타입을 String이 아닌 List로 변경
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#195 refactor: 가게 검색 결과의 가게 카테고리 조회 시 categoryString 컬럼을 조회하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#196 fix: 리뷰 조회 시 status 값을 확인하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :bug: Bug

#203 release: 0.1.0-alpha.11
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/FeedDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :earth_asia: Deploy

#199 feat: GroupList 이미 존재하는 가게 추가 시 에러 발생
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#197 refactor: 타인의 루트 조회 API / feat: 정렬 조건 추가
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :hammer_and_wrench: Refactor, :sparkles: Feature

#205 release: 0.1.0-alpha.12
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#206 refactor : 이미 찜한 가게 중복 찜 불가
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#202 fix: 좋아요한 리뷰는 다시 좋아요할 수 없도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :bug: Bug

#208 fix: 리뷰 삭제했으나 리뷰가 조회되는 상황 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :bug: Bug

#209 release: 0.1.0-alpha.13
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#213 refactor: 리뷰 생성 API에서 리뷰 건너뛰기 상황도 대응할 수 있도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#211 refactor: 가게 카테고리 참조를 categoryString으로 변경
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#214 release: 0.1.0-alpha.14
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :earth_asia: Deploy

#215 fix: 팔로워 리스트 조회 시 본인을 return하지 않도록 수정
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :bug: Bug, :earth_asia: Deploy

#216 fix : 가게 조회 시 이미지가 한 가게 리뷰 이미지만 보이는 현상 해결
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
Labels: :bug: Bug

#219 fix: 리뷰 생성 시 user의 review_cnt가 증가하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :bug: Bug

#222 fix: 리뷰 삭제 시 user의 reviewCnt가 감소하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/controller/ReviewController.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :bug: Bug

#224 fix : 찜한 경우 user의 pin_cnt가 증가하도록 변경
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :bug: Bug

#225 fix : 찜한 경우 user의 pin_cnt가 증가하도록 변경
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/PinServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
Labels: :bug: Bug

#227 refactor: 랜덤 피드, 검색 엔진 API 결과 개수 제한하기
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#228 release: 0.1.0-alpha.18
  gusto/build.gradle
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :earth_asia: Deploy
