Repository gusto-umc/Gusto-Server, pull requests merged in 2024-07, with the labels that each got.

#279 refactor : 찜한 가게 목록 조회 시 카테고리 다중 처리 및 방문 여부 조건 수정
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#280 feat: oauth 로그인 방식 변경
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#281 release: 0.3.0
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#284 hotfix: 소셜 에러 케이스 별 에러 메세지 분리
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#287 hotfix: 소셜 에러 케이스 별 에러 메세지 분리
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :hammer_and_wrench: Refactor

#273 feat: 현재 지역의 찜한 방문/미방문 식당 조회
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetPinStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#276 feat : 내 카테고리 개별/전체 공개 여부에 따른 수정 및 추가
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/CreateMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/request/UpdateMyCategoryRequest.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#283 Feat: 루트 공개 비공개 여부
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteListController.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/request/RouteRequest.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :sparkles: Feature

#291 [hotfix] user Parameter를 미제공으로 인한 오류 수정
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :bug: Bug

#294 refactor : 내 카테고리는 private 값이여도 확인 가능하게 수정
  gusto/.idea/deployment.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PinByMyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#295 hotfix : 내 카테고리는 private 값이여도 확인 가능하게 수정
  gusto/.idea/deployment.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PinByMyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :bug: Bug

#296 fix: 페이징 오류 처리 & 리뷰 공개, 비공개에 따른 crud와 모아보기, 랜덤 피드 수정
  .idea/compiler.xml
  gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/SearchFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/common/PublishStatus.java
Labels: :bug: Bug, :hammer_and_wrench: Refactor

#298 [refactor] 내 루트 조회할 때나 루트 상세 조회 시 공개/비공개 여부 포함하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteRouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#299 feat: 회원 탈퇴 및 소셜 연동 해제
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :bug: Bug, :sparkles: Feature

#301 refactor : 토큰 반환이 필요 없는 API 토큰 삭제 처리
  gusto/.idea/inspectionProfiles/Project_Default.xml
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#302 release: 0.5.0
  .idea/compiler.xml
  gusto/.idea/inspectionProfiles/Project_Default.xml
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/MyCategoryResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/controller/FeedController.java
  gusto/src/main/java/com/umc/gusto/domain/review/entity/Review.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/CreateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/request/UpdateReviewRequest.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/ReviewResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/SearchFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RouteRouteListResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteListServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/User.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/common/PublishStatus.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy
