Repository gusto-umc/Gusto-Server, pull requests merged in 2024-10, with the labels that each got.

#319 refactor : townName을 사용하는 API townCode를 사용하도록 변경
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#320 release: 0.3.8
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#321 refactor: 검색 시 대소문자, 공백 무시 & 가게 검색 페이징 처리
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/SearchStoreResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/repository/StoreRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#323 feat: 소셜 로그인 정보 암호화
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#324 chore: 엔티티 수정
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Category.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/State.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
Labels: :gear: Setting

#325 release: 0.7.0
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Category.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/City.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/State.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Store.java
  gusto/src/main/java/com/umc/gusto/domain/store/entity/Town.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/SocialService.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/UserDetailsService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy
