Repository gusto-umc/Gusto-Server, pull requests merged in 2024-08, with the labels that each got.

#303 refactor: 코드 리팩토링(transaction, 필드명 변경 등)
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#304 feat: 프로필 업데이트 시 기본 이미지 사용 케이스 추가
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feature

#305 release: 0.5.1
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/UserRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :earth_asia: Deploy

#310 refactor : privateCategory가 private일 경우 카테고리 수정 안되는 코드 수정
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
Labels: :hammer_and_wrench: Refactor

#311 release: 0.5.2
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
Labels: :earth_asia: Deploy

#306 refactor: 리뷰 service 단 트랜잭션 처리
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#307 refactor: valid & validated 처리, ConstraintViolationException 핸들러 수정
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
Labels: :hammer_and_wrench: Refactor

#312 fix: 랜덤 피드 API 관련 repository에서 VO를 사용하지 않아 발생한 문제 해결
  .idea/compiler.xml
  .idea/modules/gusto.main.iml
  .idea/sqldialects.xml
  gusto/src/main/java/com/umc/gusto/domain/review/model/FeedVO.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
Labels: :bug: Bug

#313 fix: getReview()의 review.public 체크 삭제
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
Labels: :bug: Bug

#314 feat: 페이징 처리에 필요한 storeId 값 추가 반환
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetPinStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#315 release: 0.5.3
  .idea/compiler.xml
  .idea/modules/gusto.main.iml
  .idea/sqldialects.xml
  gusto/src/main/java/com/umc/gusto/domain/review/model/FeedVO.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/RandomFeedResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/FeedServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetPinStoreInfoResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/PublishingInfoRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/UpdateProfileRequest.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/JwtService.java
  gusto/src/main/java/com/umc/gusto/global/exception/handler/GlobalExceptionHandler.java
Labels: :earth_asia: Deploy
