Repository gusto-umc/Gusto-Server, pull requests merged in 2024-04, with the labels that each got.

#230 refactor : 현재 지역의 카테고리 별 찜한 가게 목록 방문여부 필터링 추가
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#233 feat : 페이징 작업(내 카테고리)
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#235 fix: 팔로워 목록 / 팔로잉 목록의 페이징/정렬 수정
  gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
Labels: :bug: Bug, :sparkles: Feature, :warning: invalid

#236 feat: 내/타인의/그룹의 루트 페이징 기능: 루트 커서 기반으로 다음 루트 전달
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :sparkles: Feature

#237 feat: 커서 페이징 작업 (그룹 목록/ 그룹 구성원 목록)
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
Labels: :sparkles: Feature

#239 feat:그룹 내 찜한 식당 페이징 : 커서 기반 오름차순 정렬로 다음 찜한 식당 전달
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
Labels: :sparkles: Feature

#240 feat: 소셜 로그인 2.0
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/NicknameResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#241 release: 0.2.1
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/entity/Social.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignInRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/request/SignUpRequest.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/NicknameResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/SocialRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/auth/CustomAuthenticationSuccessHandler.java
  gusto/src/main/java/com/umc/gusto/global/auth/OAuthService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy

#242 fix:그룹 내 찜한 식당 페이징 오타 수정
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
Labels: :bug: Bug

#243 hotfix: 로그인 api의 엔드 포인트 수정
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
Labels: :bug: Bug

#244 hotfix: 로그인 api의 엔드 포인트 수정
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
Labels: :bug: Bug

#246 hotfix: 그룹 내 찜한 식당 페이징 오타 수정
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
Labels: :bug: Bug

#248 refactor: 그룹 페이징 로직 개선 / 가게 반환값 개수를 10개로 제한
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#249 feat: 팔로워/팔로잉 목록 조회 시 hasNext 여부를 반환
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#253 feat : 카테고리와 리뷰 페이징 처리 시 hasNext 변수 반환
  .idea/Gusto-Server.iml
  .idea/compiler.xml
  .idea/misc.xml
  gusto/.idea/gradle.xml
  gusto/.idea/misc.xml
  gusto/.idea/modules/gusto.main.iml
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
Labels: :sparkles: Feature

#254 refactor: hasNext 추가로 다음 페이지 존재 여부에 대한 정보 전달
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RoutePagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#255 release: 0.2.2
  .idea/Gusto-Server.iml
  .idea/compiler.xml
  .idea/misc.xml
  gusto/.idea/gradle.xml
  gusto/.idea/misc.xml
  gusto/.idea/modules/gusto.main.iml
  gusto/.idea/uiDesigner.xml
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/controller/MyCategoryController.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/model/response/CollectReviewsResponse.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/controller/RouteController.java
  gusto/src/main/java/com/umc/gusto/domain/route/model/response/RoutePagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/store/controller/StoreController.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/GetStoreDetailResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreService.java
  gusto/src/main/java/com/umc/gusto/domain/store/service/StoreServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/user/controller/UserController.java
  gusto/src/main/java/com/umc/gusto/domain/user/model/response/PagingResponse.java
  gusto/src/main/java/com/umc/gusto/domain/user/repository/FollowRepository.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserService.java
  gusto/src/main/java/com/umc/gusto/domain/user/service/UserServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy
