Repository gusto-umc/Gusto-Server, pull requests merged in 2025-02, with the labels that each got.

#326 hotfix: #308 PR에서 commit된 오타 수정
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/PinRepository.java
Labels: :bug: Bug

#327 Feat: 백엔드 테스트 시 토큰 발급을 위한 API
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :sparkles: Feature

#328 refactor: 리뷰 피드 API 조회 실패 시 빈 리스트 반환하도록 수정
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
Labels: :hammer_and_wrench: Refactor

#329 release: 0.8.0
  gusto/src/main/java/com/umc/gusto/domain/group/controller/GroupController.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupMemberRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/repository/GroupRepository.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupService.java
  gusto/src/main/java/com/umc/gusto/domain/group/service/GroupServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/entity/MyCategory.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/repository/MyCategoryRepository.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryService.java
  gusto/src/main/java/com/umc/gusto/domain/myCategory/service/MyCategoryServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/LikedRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/repository/ReviewRepository.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/CollectReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewService.java
  gusto/src/main/java/com/umc/gusto/domain/review/service/ReviewServiceImpl.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/Route.java
  gusto/src/main/java/com/umc/gusto/domain/route/entity/RouteList.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteListRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/repository/RouteRepository.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteService.java
  gusto/src/main/java/com/umc/gusto/domain/route/service/RouteServiceImpl.java
  gusto/src/main/java/com/umc/gusto/global/DeleteSchedulingConfig.java
  gusto/src/main/java/com/umc/gusto/global/auth/AuthController.java
  gusto/src/main/java/com/umc/gusto/global/auth/service/AuthService.java
  gusto/src/main/java/com/umc/gusto/global/exception/Code.java
Labels: :earth_asia: Deploy
